root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main cmd/main.go"
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
include_dir = []
exclude_file = []
delay = 1000 # ms
stop_on_error = true
log = "air_errors.log"

[screen]
clear_on_rebuild = true

