# Choose whatever you want, version >= 1.16
FROM golang:1.23-alpine

WORKDIR /usr/src/app

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

EXPOSE 3080

CMD ["air", "-c", ".air.toml"]
